repos:
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 6b63472e72e1a91ed8a2f6d483790dfb644fa1d3  # frozen: 0.37.4
    hooks:
      - id: check-dependabot
      - id: check-github-workflows
      - id: check-github-actions
      - id: check-github-issue-config
      - id: check-github-issue-forms
      - id: check-readthedocs
      - id: check-compose-spec

  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca  # frozen: v1.7.12
    hooks:
      - id: actionlint

  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: 64a97fb7fa63188393d3215c6e312f5f9c6d0f78  # frozen: v1.27.0
    hooks:
      - id: zizmor

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 2700fd5671c633760d912769c041bfcde2b9a01b  # frozen: v0.15.22
    hooks:
      - id: ruff-check
        args: ["--exit-non-zero-on-fix"]
      - id: ruff-format

  - repo: https://github.com/crate-ci/typos
    rev: 96d9af6217dc2855210655af7e1ff19d23d4e593  # frozen: v1
    hooks:
      - id: typos

  - repo: https://github.com/codespell-project/codespell
    rev: 57b21406f092110c18776e39b0bda50d37c945c8  # frozen: v2.4.3
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-xml
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-illegal-windows-names
      - id: check-case-conflict

  - repo: meta
    hooks:
      - id: check-useless-excludes

ci:
  autofix_prs: true
  autoupdate_schedule: weekly
  submodules: false
